version: '3.8'

services:
    app:
        image: openjdk:17-jdk-slim
        container_name: springboot-bankapp
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8081:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bankapp
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: rootpassword
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: bankapp
            MYSQL_USER: bankuser
            MYSQL_PASSWORD: bankpassword
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data: